# Generated by Django 2.0.2 on 2018-07-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180722_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['author', '-pub_date']},
        ),
    ]
